version: "3.8"

services: 
  app:
    build: 
      context: .
      dockerfile: frontend/Dockerfile
    ports: 
      - 3000:3000
    volumes: 
      - .:/app
  server:
      build: 
        context: .
        dockerfile: backend/Dockerfile
      ports: 
        - 8000:8000
      volumes: 
        - .:/app




  